services:
  app:
    image: upload-share
    restart: unless-stopped
    user: 3080:3080
    ports:
      - "127.0.0.1:3080:3000"
    volumes:
      - ./media:/app/data
    environment:
      - UPLOAD_TOKEN=${UPLOAD_TOKEN}
      - ORIGIN=${ORIGIN}
      - MAX_ARCHIVE_SIZE=${MAX_ARCHIVE_SIZE}
      - BODY_SIZE_LIMIT=107374182400
