services:
  caddy:
    image: caddy:2.11.3-alpine
    restart: unless-stopped
    user: 3070:3070
    environment:
      CADDY_BASICAUTH: ${CADDY_BASICAUTH}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../syncthing/media/Archive:/srv/Archive:ro
    ports:
      - 127.0.0.1:3070:80
